### PR TITLE
fix: make dropping partition/table/rollup, adding partition idempotent

### LINKED ISSUE #417: `DROP_PARTITION`

### PR DESCRIPTION
**Pull request by wyxxxcat**
close #417,#418,#419,#420

### CODE REVIEW

File: pkg/ccr/base/spec.go [hunk 1]
```diff
@@ -1481,10 +1466,32 @@ func (s *Spec) RenameRollup(destTableName, oldRollup, newRollup string) error {
...
+	sort.Strings(descTableRes)
+
+	if index := sort.SearchStrings(descTableRes, rollup); index < len(descTableRes) && descTableRes[index] == rollup {
+		rollup = utils.FormatKeywordName(rollup)
+		dropRollupSql := fmt.Sprintf("ALTER TABLE %s.%s DROP ROLLUP %s", dbName, destTableName, rollup)
+		log.Infof("drop rollup sql: %s", dropRollupSql)
+		return s.Exec(dropRollupSql)
+	}
+	log.Info(fmt.Sprintf("rollup %s not found in %s, skip drop rollup", rollup, destTableName))
+	return nil
```
Comment (w41ter) [inline pkg/ccr/base/spec.go]: There is no need to check the table description here. Altering the table directly is enough.

**Review by w41ter — CHANGES_REQUESTED** [review]

File: pkg/ccr/base/spec.go [hunk 2]
```diff
@@ -1481,10 +1466,32 @@ func (s *Spec) RenameRollup(destTableName, oldRollup, newRollup string) error {
...
+func (s *Spec) CheckRollupIndexExists(destTableName, rollup string) (bool, error) {
+	descTableRes, err := s.queryResult(fmt.Sprintf("DESC %s.%s ALL", s.Database, destTableName), "IndexName", "DESC TABLE")
+	if err != nil {
+		return false, xerror.Wrap(err, xerror.Normal, fmt.Sprintf("desc table %s failed", destTableName))
+	}
+	sort.Strings(descTableRes)
+	if index := sort.SearchStrings(descTableRes, rollup); index < len(descTableRes) && descTableRes[index] == rollup {
+		return true, nil
+	}
+	return false, nil
```
Comment (w41ter) [inline pkg/ccr/base/spec.go]: Move this function to meta.go

File: pkg/ccr/base/spec.go [hunk 3]
```diff
@@ -1481,10 +1466,32 @@ func (s *Spec) RenameRollup(destTableName, oldRollup, newRollup string) error {
...
+	return nil
+}
+
+func (s *Spec) CheckRollupIndexExists(destTableName, rollup string) (bool, error) {
+	descTableRes, err := s.queryResult(fmt.Sprintf("DESC %s.%s ALL", s.Database, destTableName), "IndexName", "DESC TABLE")
+	if err != nil {
+		return false, xerror.Wrap(err, xerror.Normal, fmt.Sprintf("desc table %s failed", destTableName))
+	}
+	sort.Strings(descTableRes)
+	if index := sort.SearchStrings(descTableRes, rollup); index < len(descTableRes) && descTableRes[index] == rollup {
```
Comment (w41ter) [inline pkg/ccr/base/spec.go]: `slice.Contains` is enough

File: pkg/ccr/base/spec.go [hunk 4]
```diff
@@ -1481,10 +1466,32 @@ func (s *Spec) RenameRollup(destTableName, oldRollup, newRollup string) error {
...
+		dropRollupSql := fmt.Sprintf("ALTER TABLE %s.%s DROP ROLLUP %s", dbName, destTableName, rollup)
+		log.Infof("drop rollup sql: %s", dropRollupSql)
+		return s.Exec(dropRollupSql)
+	}
+	log.Info(fmt.Sprintf("rollup %s not found in %s, skip drop rollup", rollup, destTableName))
+	return nil
+}
+
+func (s *Spec) CheckRollupIndexExists(destTableName, rollup string) (bool, error) {
+	descTableRes, err := s.queryResult(fmt.Sprintf("DESC %s.%s ALL", s.Database, destTableName), "IndexName", "DESC TABLE")
```
Comment (w41ter) [inline pkg/ccr/base/spec.go]: db = utils.FormatKeywordName(s.Database)
tableName = utils.FormatKeywordName(destTableName)

File: pkg/ccr/base/spec.go [hunk 5]
```diff
@@ -1566,6 +1573,12 @@ func correctAddPartitionSql(addPartitionSql string, addPartition *record.AddPart
 	if addPartition.IsTemp && !strings.Contains(addPartitionSql, "ADD TEMPORARY PARTITION") {
 		addPartitionSql = strings.ReplaceAll(addPartitionSql, "ADD PARTITION", "ADD TEMPORARY PARTITION")
 	}
+	if strings.Contains(addPartitionSql, "ADD PARTITION") {
+		addPartitionSql = strings.ReplaceAll(addPartitionSql, "ADD PARTITION", "ADD PARTITION IF NOT EXISTS")
+	} else {
+		addPartitionSql = strings.ReplaceAll(addPartitionSql, "ADD TEMPORARY PARTITION", "ADD TEMPORARY PARTITION IF NOT EXISTS")
+	}
+	log.Infof("add partition sql: %s", addPartitionSql)
```
Comment (w41ter) [inline pkg/ccr/base/spec.go]:
```suggestion
```

**Review by w41ter — CHANGES_REQUESTED** [review]

File: pkg/ccr/base/spec.go (hunk 3 above)
Comment (w41ter) [reply pkg/ccr/base/spec.go]: It seems that the `slice` pkg was added in go 1.24. You would use `utils.Contains` which is defined in https://github.com/selectdb/ccr-syncer/pull/416/.

File: pkg/ccr/meta.go [hunk 6]
```diff
@@ -1278,12 +1279,50 @@ func (m *Meta) DescribeTable(tableName string) ([]*ColumnDesc, error) {
...
+		if isNext {
+			indexName, err = rowParser.GetString("IndexName")
+			isNext = false
+			if err != nil {
+				return nil, xerror.Wrapf(err, xerror.Normal, "describe table get Field failed, table: %s", tableName)
+			}
+		}
+
+		indexKeysType := ""
+		if isNext {
```
Comment (w41ter) [inline pkg/ccr/meta.go]: isNext is always false here.

File: pkg/ccr/meta.go [hunk 7]
```diff
@@ -1278,12 +1279,50 @@ func (m *Meta) DescribeTable(tableName string) ([]*ColumnDesc, error) {
...
+			indexKeysType, err = rowParser.GetString("IndexName")
+			isNext = false
+			if err != nil {
+				return nil, xerror.Wrapf(err, xerror.Normal, "describe table get Field failed, table: %s", tableName)
```
Comment (w41ter) [inline pkg/ccr/meta.go]:
```suggestion
				return nil, xerror.Wrapf(err, xerror.Normal, "describe table get IndexKeysType failed, table: %s", tableName)
```

File: pkg/ccr/meta.go [hunk 8]
```diff
@@ -1278,12 +1279,50 @@ func (m *Meta) DescribeTable(tableName string) ([]*ColumnDesc, error) {
...
+			isNext = true
+			continue
+		}
+
+		indexName := ""
+		if isNext {
+			indexName, err = rowParser.GetString("IndexName")
+			isNext = false
+			if err != nil {
+				return nil, xerror.Wrapf(err, xerror.Normal, "describe table get Field failed, table: %s", tableName)
```
Comment (w41ter) [inline pkg/ccr/meta.go]:
```suggestion
				return nil, xerror.Wrapf(err, xerror.Normal, "describe table get IndexName failed, table: %s", tableName)
```

File: pkg/ccr/meta.go [hunk 9]
```diff
@@ -1278,12 +1279,50 @@ func (m *Meta) DescribeTable(tableName string) ([]*ColumnDesc, error) {
...
+			}
+		}
+
+		indexKeysType := ""
+		if isNext {
+			indexKeysType, err = rowParser.GetString("IndexName")
```
Comment (w41ter) [inline pkg/ccr/meta.go]: IndexKeysType

File: pkg/ccr/meta.go [hunk 10]
```diff
@@ -1278,12 +1279,50 @@ func (m *Meta) DescribeTable(tableName string) ([]*ColumnDesc, error) {
...
+
 		// get Type, Null, Key, Default, Extra
 		typ, err := rowParser.GetString("Type")
 		if err != nil {
 			return nil, xerror.Wrapf(err, xerror.Normal, "describe table get Type failed, table: %s", tableName)
 		}
 
+		internalType, err := rowParser.GetString("InternalType")
+		if err != nil {
+			return nil, xerror.Wrapf(err, xerror.Normal, "describe table get Type failed, table: %s", tableName)
```
Comment (w41ter) [inline pkg/ccr/meta.go]:
```suggestion
			return nil, xerror.Wrapf(err, xerror.Normal, "describe table get InternalType failed, table: %s", tableName)
```

File: pkg/ccr/meta.go [hunk 11]
```diff
@@ -1304,18 +1343,33 @@ func (m *Meta) DescribeTable(tableName string) ([]*ColumnDesc, error) {
 			return nil, xerror.Wrapf(err, xerror.Normal, "describe table get Extra failed, table: %s", tableName)
 		}
 
+		visible, err := rowParser.GetString("Visible")
+		if err != nil {
+			return nil, xerror.Wrapf(err, xerror.Normal, "describe table get Extra failed, table: %s", tableName)
```
Comment (w41ter) [inline pkg/ccr/meta.go]:
```suggestion
			return nil, xerror.Wrapf(err, xerror.Normal, "describe table get Visible failed, table: %s", tableName)
```

File: pkg/ccr/metaer.go [hunk 12]
```diff
@@ -82,13 +82,21 @@ type ReplicaMeta struct {
 	Version    int64
 }
 
+type ColumnDescAll struct {
+	IndexName     string
+	IndexKeysType string
+	ColumnDesc    map[string]ColumnDesc
```
Comment (w41ter) [inline pkg/ccr/metaer.go]:
```suggestion
	ColumnDesc    []ColumnDesc
```

File: pkg/ccr/meta.go [hunk 13]
```diff
@@ -1304,18 +1343,33 @@ func (m *Meta) DescribeTable(tableName string) ([]*ColumnDesc, error) {
...
+					Name:         name,
+					Type:         typ,
+					InternalType: internalType,
+					IsNull:       isNull,
+					IsKey:        isKey,
+					Default:      defaultValue,
+					Extra:        extra,
+					Visible:      isVisible,
+				},
+			},
```
Comment (w41ter) [inline pkg/ccr/meta.go]: Describe tables return many indexes, each index has many column descs.

Consider:
```
if materializedIndex, ok := materializedIndexes[IndexName]; ok {
	materializedIndex.ColumnDescs = append(materializedIndex.ColumnDescs, desc)
} else {
    materializedIndexes[IndexName] = MaterializedIndexDesc {
		IndexName: ...
		....
	}
}
```

File: pkg/ccr/metaer.go [hunk 14]
```diff
@@ -82,13 +82,21 @@ type ReplicaMeta struct {
 	Version    int64
 }
 
+type ColumnDescAll struct {
```
Comment (w41ter) [inline pkg/ccr/metaer.go]:
```suggestion
type MaterializedIndexDesc struct {
```

The describe tables command returns `MaterializedIndex` in doris.

File: pkg/ccr/job.go [hunk 15]
```diff
@@ -3072,6 +3077,30 @@ func (j *Job) isModifyTableColumnsCommitted(record *record.ModifyTableAddOrDropC
 	return true, nil
 }
 
+func (j *Job) isDropRollupCommitted(record *record.DropRollup) (bool, error) {
+	var destTableName string
+	if j.SyncType == TableSync {
+		destTableName = j.Dest.Table
+	} else {
+		destTableName = record.TableName
+	}
```
Comment (w41ter) [inline pkg/ccr/job.go]: j.getDestTableNameById(record.TableId)

File: pkg/ccr/job.go [hunk 16]
```diff
@@ -3072,6 +3077,30 @@ func (j *Job) isModifyTableColumnsCommitted(record *record.ModifyTableAddOrDropC
...
+		log.Debugf("Desc result: %v, %v", colDesc.IndexName, colDesc.ColumnDesc)
+	}
+	if err != nil {
+		return false, err
+	}
+	indexNames := []string{}
+	for _, colDesc := range descResult {
+		indexNames = append(indexNames, colDesc.IndexName)
+	}
+	if exists := slices.Contains(indexNames, record.IndexName); !exists {
```
Comment (w41ter) [inline pkg/ccr/job.go]:
```suggestion
	if !slices.Contains(indexNames, record.IndexName) {
```

Comment (w41ter) [reply pkg/ccr/job.go]: Or

```suggestion
	return slices.Contains(indexNames, record.IndexName), nil
```

File: pkg/ccr/job.go [hunk 17]
```diff
@@ -3034,14 +3035,17 @@ func (j *Job) isModifyTableColumnsCommitted(record *record.ModifyTableAddOrDropC
...
 	if err != nil {
 		return false, err
 	}
 
+	log.Debugf("desc all table: %v", columns)
+
 	destColumnMap := make(map[string]struct{})
 	for _, col := range columns {
-		destColumnMap[col.Name] = struct{}{}
+		name := col.ColumnDesc[col.IndexName].Name
```
Comment (w41ter) [inline pkg/ccr/job.go]: Only the base index is considered here.

Take base materialized index desc:

```
materializedIndexes, err := j.destMeta.DescribeTableAll(tableName)
var baseIndex *MaterializedIndexDesc
for i, index := range materializedIndexes {
	if index.IndexName == tableName {
		baseIndex = &materializedIndexes[i]
		break
	}
}
```

Or you could simple returns a `map[string]MaterializedIndexDesc` in `DescribeTableAll`.

**Review by w41ter — CHANGES_REQUESTED** [review]

File: pkg/ccr/base/spec.go [hunk 18]
```diff
@@ -1379,7 +1359,11 @@ func (s *Spec) AddPartition(destTableName string, addPartition *record.AddPartit
 func (s *Spec) DropPartition(destTableName string, dropPartition *record.DropPartition) error {
 	dbName := utils.FormatKeywordName(s.Database)
 	destTableName = utils.FormatKeywordName(destTableName)
-	dropPartitionSql := fmt.Sprintf("ALTER TABLE %s.%s %s", dbName, destTableName, dropPartition.Sql)
+	forceDrop := ""
+	if dropPartition.ForceDrop {
+		forceDrop = "FORCE"
+	}
+	dropPartitionSql := fmt.Sprintf("ALTER TABLE %s.%s DROP PARTITION IF EXISTS %s %s", dbName, destTableName, dropPartition.PartitionName, forceDrop)
```
Comment (w41ter) [inline pkg/ccr/base/spec.go]:
```suggestion
	dropPartitionSql := fmt.Sprintf("ALTER TABLE %s.%s DROP PARTITION IF EXISTS %s %s", dbName, destTableName, utils.FormatKeywordName(dropPartition.PartitionName), forceDrop)
```

File: pkg/ccr/job.go [hunk 19]
```diff
@@ -3034,13 +3034,16 @@ func (j *Job) isModifyTableColumnsCommitted(record *record.ModifyTableAddOrDropC
 		return false, err
 	}
 
-	columns, err := j.destMeta.DescribeTable(tableName)
+	materializedIndexes, err := j.destMeta.DescribeTableAll(tableName)
 	if err != nil {
 		return false, err
 	}
+	var baseIndex *MaterializedIndexDesc = materializedIndexes[tableName]
```
Comment (w41ter) [inline pkg/ccr/job.go]:
```suggestion
	baseIndex := materializedIndexes[tableName]
```

**Review by w41ter — APPROVED** [review]
